# Site settings
title: Michael Dowse
email: hi@michaeldowse.name
description: > # this means to ignore newlines until "baseurl:"
  Software Developer, reader, and occasional blogger.
  Founder of Go Vocab.
  Born and raised in Wellington, New Zealand.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://michael.dowse.co.nz" # the base hostname & protocol for your site
twitter_username: michaeldowse
github_username:  michaeldowse
excerpt_separator: <!--more-->
paginate: 12
gems:
  - jekyll-feed
  - jekyll-paginate

# Build settings
markdown: kramdown
encoding: utf-8

plugins:
  - jekyll-paginate
  - jekyll-feed

collections:
  pages:
    output: true
